// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: transform.proto

package options

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageKind int32

const (
	MessageKind_MESSAGE_KIND_UNSPECIFIED MessageKind = 0
	MessageKind_MESSAGE_KIND_REQUEST     MessageKind = 1
	MessageKind_MESSAGE_KIND_RESPONSE    MessageKind = 2
	MessageKind_MESSAGE_KIND_NOTIFY      MessageKind = 3
)

// Enum value maps for MessageKind.
var (
	MessageKind_name = map[int32]string{
		0: "MESSAGE_KIND_UNSPECIFIED",
		1: "MESSAGE_KIND_REQUEST",
		2: "MESSAGE_KIND_RESPONSE",
		3: "MESSAGE_KIND_NOTIFY",
	}
	MessageKind_value = map[string]int32{
		"MESSAGE_KIND_UNSPECIFIED": 0,
		"MESSAGE_KIND_REQUEST":     1,
		"MESSAGE_KIND_RESPONSE":    2,
		"MESSAGE_KIND_NOTIFY":      3,
	}
)

func (x MessageKind) Enum() *MessageKind {
	p := new(MessageKind)
	*p = x
	return p
}

func (x MessageKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageKind) Descriptor() protoreflect.EnumDescriptor {
	return file_transform_proto_enumTypes[0].Descriptor()
}

func (MessageKind) Type() protoreflect.EnumType {
	return &file_transform_proto_enumTypes[0]
}

func (x MessageKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageKind.Descriptor instead.
func (MessageKind) EnumDescriptor() ([]byte, []int) {
	return file_transform_proto_rawDescGZIP(), []int{0}
}

var file_transform_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*uint32)(nil),
		Field:         51001,
		Name:          "transformgen.options.message_id",
		Tag:           "varint,51001,opt,name=message_id",
		Filename:      "transform.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*MessageKind)(nil),
		Field:         51002,
		Name:          "transformgen.options.message_kind",
		Tag:           "varint,51002,opt,name=message_kind,enum=transformgen.options.MessageKind",
		Filename:      "transform.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*uint32)(nil),
		Field:         51003,
		Name:          "transformgen.options.message_id_min",
		Tag:           "varint,51003,opt,name=message_id_min",
		Filename:      "transform.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*uint32)(nil),
		Field:         51004,
		Name:          "transformgen.options.message_id_max",
		Tag:           "varint,51004,opt,name=message_id_max",
		Filename:      "transform.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional uint32 message_id = 51001;
	E_MessageId = &file_transform_proto_extTypes[0]
	// optional transformgen.options.MessageKind message_kind = 51002;
	E_MessageKind = &file_transform_proto_extTypes[1]
)

// Extension fields to descriptorpb.FileOptions.
var (
	// optional uint32 message_id_min = 51003;
	E_MessageIdMin = &file_transform_proto_extTypes[2]
	// optional uint32 message_id_max = 51004;
	E_MessageIdMax = &file_transform_proto_extTypes[3]
)

var File_transform_proto protoreflect.FileDescriptor

const file_transform_proto_rawDesc = "" +
	"\n" +
	"\x0ftransform.proto\x12\x14transformgen.options\x1a google/protobuf/descriptor.proto*y\n" +
	"\vMessageKind\x12\x1c\n" +
	"\x18MESSAGE_KIND_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14MESSAGE_KIND_REQUEST\x10\x01\x12\x19\n" +
	"\x15MESSAGE_KIND_RESPONSE\x10\x02\x12\x17\n" +
	"\x13MESSAGE_KIND_NOTIFY\x10\x03:@\n" +
	"\n" +
	"message_id\x12\x1f.google.protobuf.MessageOptions\x18\xb9\x8e\x03 \x01(\rR\tmessageId:g\n" +
	"\fmessage_kind\x12\x1f.google.protobuf.MessageOptions\x18\xba\x8e\x03 \x01(\x0e2!.transformgen.options.MessageKindR\vmessageKind:D\n" +
	"\x0emessage_id_min\x12\x1c.google.protobuf.FileOptions\x18\xbb\x8e\x03 \x01(\rR\fmessageIdMin:D\n" +
	"\x0emessage_id_max\x12\x1c.google.protobuf.FileOptions\x18\xbc\x8e\x03 \x01(\rR\fmessageIdMaxB:Z8github.com/wxdqing/go-transformgen/proto/options;optionsb\x06proto3"

var (
	file_transform_proto_rawDescOnce sync.Once
	file_transform_proto_rawDescData []byte
)

func file_transform_proto_rawDescGZIP() []byte {
	file_transform_proto_rawDescOnce.Do(func() {
		file_transform_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transform_proto_rawDesc), len(file_transform_proto_rawDesc)))
	})
	return file_transform_proto_rawDescData
}

var file_transform_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_transform_proto_goTypes = []any{
	(MessageKind)(0),                    // 0: transformgen.options.MessageKind
	(*descriptorpb.MessageOptions)(nil), // 1: google.protobuf.MessageOptions
	(*descriptorpb.FileOptions)(nil),    // 2: google.protobuf.FileOptions
}
var file_transform_proto_depIdxs = []int32{
	1, // 0: transformgen.options.message_id:extendee -> google.protobuf.MessageOptions
	1, // 1: transformgen.options.message_kind:extendee -> google.protobuf.MessageOptions
	2, // 2: transformgen.options.message_id_min:extendee -> google.protobuf.FileOptions
	2, // 3: transformgen.options.message_id_max:extendee -> google.protobuf.FileOptions
	0, // 4: transformgen.options.message_kind:type_name -> transformgen.options.MessageKind
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	4, // [4:5] is the sub-list for extension type_name
	0, // [0:4] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_transform_proto_init() }
func file_transform_proto_init() {
	if File_transform_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transform_proto_rawDesc), len(file_transform_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 4,
			NumServices:   0,
		},
		GoTypes:           file_transform_proto_goTypes,
		DependencyIndexes: file_transform_proto_depIdxs,
		EnumInfos:         file_transform_proto_enumTypes,
		ExtensionInfos:    file_transform_proto_extTypes,
	}.Build()
	File_transform_proto = out.File
	file_transform_proto_goTypes = nil
	file_transform_proto_depIdxs = nil
}
