// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: example/transform/battle.proto

package examplepb

import (
	_ "github.com/wxdqing/go-transformgen/proto/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartBattleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	StageId       string                 `protobuf:"bytes,2,opt,name=stage_id,json=stageId,proto3" json:"stage_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartBattleRequest) Reset() {
	*x = StartBattleRequest{}
	mi := &file_example_transform_battle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartBattleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartBattleRequest) ProtoMessage() {}

func (x *StartBattleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_transform_battle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartBattleRequest.ProtoReflect.Descriptor instead.
func (*StartBattleRequest) Descriptor() ([]byte, []int) {
	return file_example_transform_battle_proto_rawDescGZIP(), []int{0}
}

func (x *StartBattleRequest) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *StartBattleRequest) GetStageId() string {
	if x != nil {
		return x.StageId
	}
	return ""
}

type StartBattleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BattleId      uint64                 `protobuf:"varint,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartBattleResponse) Reset() {
	*x = StartBattleResponse{}
	mi := &file_example_transform_battle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartBattleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartBattleResponse) ProtoMessage() {}

func (x *StartBattleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_example_transform_battle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartBattleResponse.ProtoReflect.Descriptor instead.
func (*StartBattleResponse) Descriptor() ([]byte, []int) {
	return file_example_transform_battle_proto_rawDescGZIP(), []int{1}
}

func (x *StartBattleResponse) GetBattleId() uint64 {
	if x != nil {
		return x.BattleId
	}
	return 0
}

func (x *StartBattleResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type BattleStateNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BattleId      uint64                 `protobuf:"varint,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleStateNotify) Reset() {
	*x = BattleStateNotify{}
	mi := &file_example_transform_battle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleStateNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleStateNotify) ProtoMessage() {}

func (x *BattleStateNotify) ProtoReflect() protoreflect.Message {
	mi := &file_example_transform_battle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleStateNotify.ProtoReflect.Descriptor instead.
func (*BattleStateNotify) Descriptor() ([]byte, []int) {
	return file_example_transform_battle_proto_rawDescGZIP(), []int{2}
}

func (x *BattleStateNotify) GetBattleId() uint64 {
	if x != nil {
		return x.BattleId
	}
	return 0
}

func (x *BattleStateNotify) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

var File_example_transform_battle_proto protoreflect.FileDescriptor

const file_example_transform_battle_proto_rawDesc = "" +
	"\n" +
	"\x1eexample/transform/battle.proto\x12\x11transform.example\x1a\x1dproto/options/transform.proto\"W\n" +
	"\x12StartBattleRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\x19\n" +
	"\bstage_id\x18\x02 \x01(\tR\astageId:\t\xc8\xf3\x18\xcd\b\xd0\xf3\x18\x01\"Y\n" +
	"\x13StartBattleResponse\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\x04R\bbattleId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted:\t\xc8\xf3\x18\xce\b\xd0\xf3\x18\x02\"Q\n" +
	"\x11BattleStateNotify\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\x04R\bbattleId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state:\t\xc8\xf3\x18\xb5\x10\xd0\xf3\x18\x03BJ\xd8\xf3\x18\xcc\b\xe0\xf3\x18\xb5\x10Z>github.com/wxdqing/go-transformgen/example/transform;examplepbb\x06proto3"

var (
	file_example_transform_battle_proto_rawDescOnce sync.Once
	file_example_transform_battle_proto_rawDescData []byte
)

func file_example_transform_battle_proto_rawDescGZIP() []byte {
	file_example_transform_battle_proto_rawDescOnce.Do(func() {
		file_example_transform_battle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_example_transform_battle_proto_rawDesc), len(file_example_transform_battle_proto_rawDesc)))
	})
	return file_example_transform_battle_proto_rawDescData
}

var file_example_transform_battle_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_example_transform_battle_proto_goTypes = []any{
	(*StartBattleRequest)(nil),  // 0: transform.example.StartBattleRequest
	(*StartBattleResponse)(nil), // 1: transform.example.StartBattleResponse
	(*BattleStateNotify)(nil),   // 2: transform.example.BattleStateNotify
}
var file_example_transform_battle_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_example_transform_battle_proto_init() }
func file_example_transform_battle_proto_init() {
	if File_example_transform_battle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_example_transform_battle_proto_rawDesc), len(file_example_transform_battle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_example_transform_battle_proto_goTypes,
		DependencyIndexes: file_example_transform_battle_proto_depIdxs,
		MessageInfos:      file_example_transform_battle_proto_msgTypes,
	}.Build()
	File_example_transform_battle_proto = out.File
	file_example_transform_battle_proto_goTypes = nil
	file_example_transform_battle_proto_depIdxs = nil
}
