// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: example/transform/chat.proto

package examplepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     uint64                 `protobuf:"varint,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendChatRequest) Reset() {
	*x = SendChatRequest{}
	mi := &file_example_transform_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendChatRequest) ProtoMessage() {}

func (x *SendChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_transform_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendChatRequest.ProtoReflect.Descriptor instead.
func (*SendChatRequest) Descriptor() ([]byte, []int) {
	return file_example_transform_chat_proto_rawDescGZIP(), []int{0}
}

func (x *SendChatRequest) GetChannelId() uint64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *SendChatRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type SendChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ret           EMsgErrorType          `protobuf:"varint,1,opt,name=ret,proto3,enum=transform.example.EMsgErrorType" json:"ret,omitempty"`
	MessageId     uint64                 `protobuf:"varint,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendChatResponse) Reset() {
	*x = SendChatResponse{}
	mi := &file_example_transform_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendChatResponse) ProtoMessage() {}

func (x *SendChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_example_transform_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendChatResponse.ProtoReflect.Descriptor instead.
func (*SendChatResponse) Descriptor() ([]byte, []int) {
	return file_example_transform_chat_proto_rawDescGZIP(), []int{1}
}

func (x *SendChatResponse) GetRet() EMsgErrorType {
	if x != nil {
		return x.Ret
	}
	return EMsgErrorType_None
}

func (x *SendChatResponse) GetMessageId() uint64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

type ChatMessageNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     uint64                 `protobuf:"varint,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	MessageId     uint64                 `protobuf:"varint,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Mentions      []string               `protobuf:"bytes,4,rep,name=mentions,proto3" json:"mentions,omitempty"`
	MentionCounts map[string]int32       `protobuf:"bytes,5,rep,name=mention_counts,json=mentionCounts,proto3" json:"mention_counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Types that are valid to be assigned to Attachment:
	//
	//	*ChatMessageNotify_TextAttachment
	//	*ChatMessageNotify_TagAttachment
	Attachment    isChatMessageNotify_Attachment `protobuf_oneof:"attachment"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessageNotify) Reset() {
	*x = ChatMessageNotify{}
	mi := &file_example_transform_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessageNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessageNotify) ProtoMessage() {}

func (x *ChatMessageNotify) ProtoReflect() protoreflect.Message {
	mi := &file_example_transform_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessageNotify.ProtoReflect.Descriptor instead.
func (*ChatMessageNotify) Descriptor() ([]byte, []int) {
	return file_example_transform_chat_proto_rawDescGZIP(), []int{2}
}

func (x *ChatMessageNotify) GetChannelId() uint64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *ChatMessageNotify) GetMessageId() uint64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *ChatMessageNotify) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessageNotify) GetMentions() []string {
	if x != nil {
		return x.Mentions
	}
	return nil
}

func (x *ChatMessageNotify) GetMentionCounts() map[string]int32 {
	if x != nil {
		return x.MentionCounts
	}
	return nil
}

func (x *ChatMessageNotify) GetAttachment() isChatMessageNotify_Attachment {
	if x != nil {
		return x.Attachment
	}
	return nil
}

func (x *ChatMessageNotify) GetTextAttachment() string {
	if x != nil {
		if x, ok := x.Attachment.(*ChatMessageNotify_TextAttachment); ok {
			return x.TextAttachment
		}
	}
	return ""
}

func (x *ChatMessageNotify) GetTagAttachment() *MsgDataTag {
	if x != nil {
		if x, ok := x.Attachment.(*ChatMessageNotify_TagAttachment); ok {
			return x.TagAttachment
		}
	}
	return nil
}

type isChatMessageNotify_Attachment interface {
	isChatMessageNotify_Attachment()
}

type ChatMessageNotify_TextAttachment struct {
	TextAttachment string `protobuf:"bytes,6,opt,name=text_attachment,json=textAttachment,proto3,oneof"`
}

type ChatMessageNotify_TagAttachment struct {
	TagAttachment *MsgDataTag `protobuf:"bytes,7,opt,name=tag_attachment,json=tagAttachment,proto3,oneof"`
}

func (*ChatMessageNotify_TextAttachment) isChatMessageNotify_Attachment() {}

func (*ChatMessageNotify_TagAttachment) isChatMessageNotify_Attachment() {}

var File_example_transform_chat_proto protoreflect.FileDescriptor

const file_example_transform_chat_proto_rawDesc = "" +
	"\n" +
	"\x1cexample/transform/chat.proto\x12\x11transform.example\x1a\x1eexample/transform/common.proto\"J\n" +
	"\x0fSendChatRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\x04R\tchannelId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"e\n" +
	"\x10SendChatResponse\x122\n" +
	"\x03ret\x18\x01 \x01(\x0e2 .transform.example.EMsgErrorTypeR\x03ret\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\x04R\tmessageId\"\xaa\x03\n" +
	"\x11ChatMessageNotify\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\x04R\tchannelId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\x04R\tmessageId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1a\n" +
	"\bmentions\x18\x04 \x03(\tR\bmentions\x12^\n" +
	"\x0emention_counts\x18\x05 \x03(\v27.transform.example.ChatMessageNotify.MentionCountsEntryR\rmentionCounts\x12)\n" +
	"\x0ftext_attachment\x18\x06 \x01(\tH\x00R\x0etextAttachment\x12F\n" +
	"\x0etag_attachment\x18\a \x01(\v2\x1d.transform.example.MsgDataTagH\x00R\rtagAttachment\x1a@\n" +
	"\x12MentionCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01B\f\n" +
	"\n" +
	"attachmentB@Z>github.com/wxdqing/go-transformgen/example/transform;examplepbb\x06proto3"

var (
	file_example_transform_chat_proto_rawDescOnce sync.Once
	file_example_transform_chat_proto_rawDescData []byte
)

func file_example_transform_chat_proto_rawDescGZIP() []byte {
	file_example_transform_chat_proto_rawDescOnce.Do(func() {
		file_example_transform_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_example_transform_chat_proto_rawDesc), len(file_example_transform_chat_proto_rawDesc)))
	})
	return file_example_transform_chat_proto_rawDescData
}

var file_example_transform_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_example_transform_chat_proto_goTypes = []any{
	(*SendChatRequest)(nil),   // 0: transform.example.SendChatRequest
	(*SendChatResponse)(nil),  // 1: transform.example.SendChatResponse
	(*ChatMessageNotify)(nil), // 2: transform.example.ChatMessageNotify
	nil,                       // 3: transform.example.ChatMessageNotify.MentionCountsEntry
	(EMsgErrorType)(0),        // 4: transform.example.EMsgErrorType
	(*MsgDataTag)(nil),        // 5: transform.example.MsgDataTag
}
var file_example_transform_chat_proto_depIdxs = []int32{
	4, // 0: transform.example.SendChatResponse.ret:type_name -> transform.example.EMsgErrorType
	3, // 1: transform.example.ChatMessageNotify.mention_counts:type_name -> transform.example.ChatMessageNotify.MentionCountsEntry
	5, // 2: transform.example.ChatMessageNotify.tag_attachment:type_name -> transform.example.MsgDataTag
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_example_transform_chat_proto_init() }
func file_example_transform_chat_proto_init() {
	if File_example_transform_chat_proto != nil {
		return
	}
	file_example_transform_common_proto_init()
	file_example_transform_chat_proto_msgTypes[2].OneofWrappers = []any{
		(*ChatMessageNotify_TextAttachment)(nil),
		(*ChatMessageNotify_TagAttachment)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_example_transform_chat_proto_rawDesc), len(file_example_transform_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_example_transform_chat_proto_goTypes,
		DependencyIndexes: file_example_transform_chat_proto_depIdxs,
		MessageInfos:      file_example_transform_chat_proto_msgTypes,
	}.Build()
	File_example_transform_chat_proto = out.File
	file_example_transform_chat_proto_goTypes = nil
	file_example_transform_chat_proto_depIdxs = nil
}
