// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: example/transform/chat.proto

package examplepb

import (
	_ "github.com/wxdqing/go-transformgen/proto/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     uint64                 `protobuf:"varint,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendChatRequest) Reset() {
	*x = SendChatRequest{}
	mi := &file_example_transform_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendChatRequest) ProtoMessage() {}

func (x *SendChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_transform_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendChatRequest.ProtoReflect.Descriptor instead.
func (*SendChatRequest) Descriptor() ([]byte, []int) {
	return file_example_transform_chat_proto_rawDescGZIP(), []int{0}
}

func (x *SendChatRequest) GetChannelId() uint64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *SendChatRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type SendChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     uint64                 `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendChatResponse) Reset() {
	*x = SendChatResponse{}
	mi := &file_example_transform_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendChatResponse) ProtoMessage() {}

func (x *SendChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_example_transform_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendChatResponse.ProtoReflect.Descriptor instead.
func (*SendChatResponse) Descriptor() ([]byte, []int) {
	return file_example_transform_chat_proto_rawDescGZIP(), []int{1}
}

func (x *SendChatResponse) GetMessageId() uint64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

type ChatMessageNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     uint64                 `protobuf:"varint,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	MessageId     uint64                 `protobuf:"varint,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessageNotify) Reset() {
	*x = ChatMessageNotify{}
	mi := &file_example_transform_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessageNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessageNotify) ProtoMessage() {}

func (x *ChatMessageNotify) ProtoReflect() protoreflect.Message {
	mi := &file_example_transform_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessageNotify.ProtoReflect.Descriptor instead.
func (*ChatMessageNotify) Descriptor() ([]byte, []int) {
	return file_example_transform_chat_proto_rawDescGZIP(), []int{2}
}

func (x *ChatMessageNotify) GetChannelId() uint64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *ChatMessageNotify) GetMessageId() uint64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *ChatMessageNotify) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_example_transform_chat_proto protoreflect.FileDescriptor

const file_example_transform_chat_proto_rawDesc = "" +
	"\n" +
	"\x1cexample/transform/chat.proto\x12\x11transform.example\x1a\x1dproto/options/transform.proto\"U\n" +
	"\x0fSendChatRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\x04R\tchannelId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent:\t\xc8\xf3\x18\xb1\t\xd0\xf3\x18\x01\"<\n" +
	"\x10SendChatResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x04R\tmessageId:\t\xc8\xf3\x18\xb2\t\xd0\xf3\x18\x02\"v\n" +
	"\x11ChatMessageNotify\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\x04R\tchannelId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\x04R\tmessageId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent:\t\xc8\xf3\x18\x99\x11\xd0\xf3\x18\x03BJ\xd8\xf3\x18\xb0\t\xe0\xf3\x18\x99\x11Z>github.com/wxdqing/go-transformgen/example/transform;examplepbb\x06proto3"

var (
	file_example_transform_chat_proto_rawDescOnce sync.Once
	file_example_transform_chat_proto_rawDescData []byte
)

func file_example_transform_chat_proto_rawDescGZIP() []byte {
	file_example_transform_chat_proto_rawDescOnce.Do(func() {
		file_example_transform_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_example_transform_chat_proto_rawDesc), len(file_example_transform_chat_proto_rawDesc)))
	})
	return file_example_transform_chat_proto_rawDescData
}

var file_example_transform_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_example_transform_chat_proto_goTypes = []any{
	(*SendChatRequest)(nil),   // 0: transform.example.SendChatRequest
	(*SendChatResponse)(nil),  // 1: transform.example.SendChatResponse
	(*ChatMessageNotify)(nil), // 2: transform.example.ChatMessageNotify
}
var file_example_transform_chat_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_example_transform_chat_proto_init() }
func file_example_transform_chat_proto_init() {
	if File_example_transform_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_example_transform_chat_proto_rawDesc), len(file_example_transform_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_example_transform_chat_proto_goTypes,
		DependencyIndexes: file_example_transform_chat_proto_depIdxs,
		MessageInfos:      file_example_transform_chat_proto_msgTypes,
	}.Build()
	File_example_transform_chat_proto = out.File
	file_example_transform_chat_proto_goTypes = nil
	file_example_transform_chat_proto_depIdxs = nil
}
