// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: example/transform/common.proto

package examplepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EMsgErrorType int32

const (
	EMsgErrorType_None            EMsgErrorType = 0
	EMsgErrorType_InvalidArgument EMsgErrorType = 1
	EMsgErrorType_NotFound        EMsgErrorType = 2
)

// Enum value maps for EMsgErrorType.
var (
	EMsgErrorType_name = map[int32]string{
		0: "None",
		1: "InvalidArgument",
		2: "NotFound",
	}
	EMsgErrorType_value = map[string]int32{
		"None":            0,
		"InvalidArgument": 1,
		"NotFound":        2,
	}
)

func (x EMsgErrorType) Enum() *EMsgErrorType {
	p := new(EMsgErrorType)
	*p = x
	return p
}

func (x EMsgErrorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EMsgErrorType) Descriptor() protoreflect.EnumDescriptor {
	return file_example_transform_common_proto_enumTypes[0].Descriptor()
}

func (EMsgErrorType) Type() protoreflect.EnumType {
	return &file_example_transform_common_proto_enumTypes[0]
}

func (x EMsgErrorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EMsgErrorType.Descriptor instead.
func (EMsgErrorType) EnumDescriptor() ([]byte, []int) {
	return file_example_transform_common_proto_rawDescGZIP(), []int{0}
}

type MsgDataTag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Weight        int32                  `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgDataTag) Reset() {
	*x = MsgDataTag{}
	mi := &file_example_transform_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgDataTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgDataTag) ProtoMessage() {}

func (x *MsgDataTag) ProtoReflect() protoreflect.Message {
	mi := &file_example_transform_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgDataTag.ProtoReflect.Descriptor instead.
func (*MsgDataTag) Descriptor() ([]byte, []int) {
	return file_example_transform_common_proto_rawDescGZIP(), []int{0}
}

func (x *MsgDataTag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MsgDataTag) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

var File_example_transform_common_proto protoreflect.FileDescriptor

const file_example_transform_common_proto_rawDesc = "" +
	"\n" +
	"\x1eexample/transform/common.proto\x12\x11transform.example\"8\n" +
	"\n" +
	"MsgDataTag\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\x05R\x06weight*<\n" +
	"\rEMsgErrorType\x12\b\n" +
	"\x04None\x10\x00\x12\x13\n" +
	"\x0fInvalidArgument\x10\x01\x12\f\n" +
	"\bNotFound\x10\x02B@Z>github.com/wxdqing/go-transformgen/example/transform;examplepbb\x06proto3"

var (
	file_example_transform_common_proto_rawDescOnce sync.Once
	file_example_transform_common_proto_rawDescData []byte
)

func file_example_transform_common_proto_rawDescGZIP() []byte {
	file_example_transform_common_proto_rawDescOnce.Do(func() {
		file_example_transform_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_example_transform_common_proto_rawDesc), len(file_example_transform_common_proto_rawDesc)))
	})
	return file_example_transform_common_proto_rawDescData
}

var file_example_transform_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_example_transform_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_example_transform_common_proto_goTypes = []any{
	(EMsgErrorType)(0), // 0: transform.example.EMsgErrorType
	(*MsgDataTag)(nil), // 1: transform.example.MsgDataTag
}
var file_example_transform_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_example_transform_common_proto_init() }
func file_example_transform_common_proto_init() {
	if File_example_transform_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_example_transform_common_proto_rawDesc), len(file_example_transform_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_example_transform_common_proto_goTypes,
		DependencyIndexes: file_example_transform_common_proto_depIdxs,
		EnumInfos:         file_example_transform_common_proto_enumTypes,
		MessageInfos:      file_example_transform_common_proto_msgTypes,
	}.Build()
	File_example_transform_common_proto = out.File
	file_example_transform_common_proto_goTypes = nil
	file_example_transform_common_proto_depIdxs = nil
}
