// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: example/transform/heartbeat.proto

package examplepb

import (
	_ "github.com/wxdqing/go-transformgen/proto/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientTime    int64                  `protobuf:"varint,1,opt,name=client_time,json=clientTime,proto3" json:"client_time,omitempty"`
	Sequence      uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_example_transform_heartbeat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_transform_heartbeat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_example_transform_heartbeat_proto_rawDescGZIP(), []int{0}
}

func (x *HeartbeatRequest) GetClientTime() int64 {
	if x != nil {
		return x.ClientTime
	}
	return 0
}

func (x *HeartbeatRequest) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerTime    int64                  `protobuf:"varint,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	ClientTime    int64                  `protobuf:"varint,2,opt,name=client_time,json=clientTime,proto3" json:"client_time,omitempty"`
	Sequence      uint64                 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_example_transform_heartbeat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_example_transform_heartbeat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_example_transform_heartbeat_proto_rawDescGZIP(), []int{1}
}

func (x *HeartbeatResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *HeartbeatResponse) GetClientTime() int64 {
	if x != nil {
		return x.ClientTime
	}
	return 0
}

func (x *HeartbeatResponse) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type BattleFinishedNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BattleId      uint64                 `protobuf:"varint,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleFinishedNotify) Reset() {
	*x = BattleFinishedNotify{}
	mi := &file_example_transform_heartbeat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleFinishedNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleFinishedNotify) ProtoMessage() {}

func (x *BattleFinishedNotify) ProtoReflect() protoreflect.Message {
	mi := &file_example_transform_heartbeat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleFinishedNotify.ProtoReflect.Descriptor instead.
func (*BattleFinishedNotify) Descriptor() ([]byte, []int) {
	return file_example_transform_heartbeat_proto_rawDescGZIP(), []int{2}
}

func (x *BattleFinishedNotify) GetBattleId() uint64 {
	if x != nil {
		return x.BattleId
	}
	return 0
}

var File_example_transform_heartbeat_proto protoreflect.FileDescriptor

const file_example_transform_heartbeat_proto_rawDesc = "" +
	"\n" +
	"!example/transform/heartbeat.proto\x12\x11transform.example\x1a\x1dproto/options/transform.proto\"Z\n" +
	"\x10HeartbeatRequest\x12\x1f\n" +
	"\vclient_time\x18\x01 \x01(\x03R\n" +
	"clientTime\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence:\t\xc8\xf3\x18\xe9\a\xd0\xf3\x18\x01\"|\n" +
	"\x11HeartbeatResponse\x12\x1f\n" +
	"\vserver_time\x18\x01 \x01(\x03R\n" +
	"serverTime\x12\x1f\n" +
	"\vclient_time\x18\x02 \x01(\x03R\n" +
	"clientTime\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence:\t\xc8\xf3\x18\xea\a\xd0\xf3\x18\x02\">\n" +
	"\x14BattleFinishedNotify\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\x04R\bbattleId:\t\xc8\xf3\x18\xd1\x0f\xd0\xf3\x18\x03BJ\xd8\xf3\x18\xe8\a\xe0\xf3\x18\xd1\x0fZ>github.com/wxdqing/go-transformgen/example/transform;examplepbb\x06proto3"

var (
	file_example_transform_heartbeat_proto_rawDescOnce sync.Once
	file_example_transform_heartbeat_proto_rawDescData []byte
)

func file_example_transform_heartbeat_proto_rawDescGZIP() []byte {
	file_example_transform_heartbeat_proto_rawDescOnce.Do(func() {
		file_example_transform_heartbeat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_example_transform_heartbeat_proto_rawDesc), len(file_example_transform_heartbeat_proto_rawDesc)))
	})
	return file_example_transform_heartbeat_proto_rawDescData
}

var file_example_transform_heartbeat_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_example_transform_heartbeat_proto_goTypes = []any{
	(*HeartbeatRequest)(nil),     // 0: transform.example.HeartbeatRequest
	(*HeartbeatResponse)(nil),    // 1: transform.example.HeartbeatResponse
	(*BattleFinishedNotify)(nil), // 2: transform.example.BattleFinishedNotify
}
var file_example_transform_heartbeat_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_example_transform_heartbeat_proto_init() }
func file_example_transform_heartbeat_proto_init() {
	if File_example_transform_heartbeat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_example_transform_heartbeat_proto_rawDesc), len(file_example_transform_heartbeat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_example_transform_heartbeat_proto_goTypes,
		DependencyIndexes: file_example_transform_heartbeat_proto_depIdxs,
		MessageInfos:      file_example_transform_heartbeat_proto_msgTypes,
	}.Build()
	File_example_transform_heartbeat_proto = out.File
	file_example_transform_heartbeat_proto_goTypes = nil
	file_example_transform_heartbeat_proto_depIdxs = nil
}
