// <auto-generated>
//   This file was generated by transformgen; do not edit.
//   Input: battle.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192

[global::ProtoBuf.ProtoContract()]
public partial class StartBattleRequest : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
    [global::ProtoBuf.ProtoMember(1)]
    public ulong PlayerId { get; set; }
    [global::ProtoBuf.ProtoMember(2)]
    [global::System.ComponentModel.DefaultValue("")]
    public string StageId { get; set; } = "";
    [global::ProtoBuf.ProtoMember(3)]
    public global::System.Collections.Generic.List<MsgDataTag> Tags { get; } = new global::System.Collections.Generic.List<MsgDataTag>();
    [global::ProtoBuf.ProtoMember(4)]
    [global::ProtoBuf.ProtoMap]
    public global::System.Collections.Generic.Dictionary<int, MsgDataTag> TagBySlot { get; } = new global::System.Collections.Generic.Dictionary<int, MsgDataTag>();

}

[global::ProtoBuf.ProtoContract()]
public partial class StartBattleResponse : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
    [global::ProtoBuf.ProtoMember(1)]
    public EMsgErrorType Ret { get; set; }
    [global::ProtoBuf.ProtoMember(2)]
    public ulong BattleId { get; set; }
    [global::ProtoBuf.ProtoMember(3)]
    public bool Accepted { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class BattleStateNotify : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
    [global::ProtoBuf.ProtoMember(1)]
    public ulong BattleId { get; set; }
    [global::ProtoBuf.ProtoMember(2)]
    [global::System.ComponentModel.DefaultValue("")]
    public string State { get; set; } = "";

}

#endregion
