// <auto-generated>
//   This file was generated by transformgen; do not edit.
//   Input: chat.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192

[global::ProtoBuf.ProtoContract()]
public partial class SendChatRequest : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
    [global::ProtoBuf.ProtoMember(1)]
    public ulong ChannelId { get; set; }
    [global::ProtoBuf.ProtoMember(2)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Content { get; set; } = "";

}

[global::ProtoBuf.ProtoContract()]
public partial class SendChatResponse : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
    [global::ProtoBuf.ProtoMember(1)]
    public EMsgErrorType Ret { get; set; }
    [global::ProtoBuf.ProtoMember(2)]
    public ulong MessageId { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class ChatMessageNotify : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
    [global::ProtoBuf.ProtoMember(1)]
    public ulong ChannelId { get; set; }
    [global::ProtoBuf.ProtoMember(2)]
    public ulong MessageId { get; set; }
    [global::ProtoBuf.ProtoMember(3)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Content { get; set; } = "";
    [global::ProtoBuf.ProtoMember(4)]
    public global::System.Collections.Generic.List<string> Mentions { get; } = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(5)]
    [global::ProtoBuf.ProtoMap]
    public global::System.Collections.Generic.Dictionary<string, int> MentionCounts { get; } = new global::System.Collections.Generic.Dictionary<string, int>();
    [global::ProtoBuf.ProtoMember(6)]
    public string TextAttachment
    {
        get => __pbn__attachment.Is(6) ? ((string)__pbn__attachment.Object) : default;
        set => __pbn__attachment = new global::ProtoBuf.DiscriminatedUnionObject(6, value);
    }
    public bool ShouldSerializeTextAttachment() => __pbn__attachment.Is(6);
    public void ResetTextAttachment() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__attachment, 6);

    private global::ProtoBuf.DiscriminatedUnionObject __pbn__attachment;
    [global::ProtoBuf.ProtoMember(7)]
    public MsgDataTag TagAttachment
    {
        get => __pbn__attachment.Is(7) ? ((MsgDataTag)__pbn__attachment.Object) : default;
        set => __pbn__attachment = new global::ProtoBuf.DiscriminatedUnionObject(7, value);
    }
    public bool ShouldSerializeTagAttachment() => __pbn__attachment.Is(7);
    public void ResetTagAttachment() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__attachment, 7);

    public AttachmentOneofCase AttachmentCase => (AttachmentOneofCase)__pbn__attachment.Discriminator;

    public enum AttachmentOneofCase
    {
        None = 0,
        TextAttachment = 6,
        TagAttachment = 7,
    }

}

#endregion
