// <auto-generated>
//   This file was generated by transformgen; do not edit.
//   Input: common.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192

[global::ProtoBuf.ProtoContract()]
public enum EMsgErrorType
{
    None = 0,
    InvalidArgument = 1,
    NotFound = 2,
}

[global::ProtoBuf.ProtoContract()]
public partial class MsgDataTag : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
    [global::ProtoBuf.ProtoMember(1)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Name { get; set; } = "";
    [global::ProtoBuf.ProtoMember(2)]
    public int Weight { get; set; }

}

#endregion
