// <auto-generated>
//   This file was generated by transformgen; do not edit.
//   Input: heartbeat.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192

[global::ProtoBuf.ProtoContract()]
public partial class HeartbeatRequest : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
    [global::ProtoBuf.ProtoMember(1)]
    public long ClientTime { get; set; }
    [global::ProtoBuf.ProtoMember(2)]
    public ulong Sequence { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class HeartbeatResponse : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
    [global::ProtoBuf.ProtoMember(1)]
    public EMsgErrorType Ret { get; set; }
    [global::ProtoBuf.ProtoMember(2)]
    public long ServerTime { get; set; }
    [global::ProtoBuf.ProtoMember(3)]
    public long ClientTime { get; set; }
    [global::ProtoBuf.ProtoMember(4)]
    public ulong Sequence { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class BattleFinishedNotify : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
    [global::ProtoBuf.ProtoMember(1)]
    public ulong BattleId { get; set; }

}

#endregion
