// Package msgidlock persists assigned protocol message ids so regenerations stay
// stable when messages are added. Deleted messages are dropped from the file and
// their ids become reusable.
package msgidlock

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

type file struct {
	Messages map[string]uint32 `yaml:"messages"`
}

// Load reads a msgid lock file. A missing file yields an empty map.
func Load(path string) (map[string]uint32, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return map[string]uint32{}, nil
		}
		return nil, err
	}
	var parsed file
	if err := yaml.Unmarshal(raw, &parsed); err != nil {
		return nil, fmt.Errorf("msgid lock %s: %w", path, err)
	}
	if parsed.Messages == nil {
		return map[string]uint32{}, nil
	}
	return parsed.Messages, nil
}

// Save writes messages sorted by name for stable diffs. Only the provided map is
// written; callers should pass the synced current set (deleted names omitted).
func Save(path string, messages map[string]uint32) error {
	names := make([]string, 0, len(messages))
	for name := range messages {
		names = append(names, name)
	}
	sort.Strings(names)

	var b strings.Builder
	b.WriteString("# Generated by transformgen. Keep in sync with protocol messages.\n")
	b.WriteString("# Existing entries are preserved across regenerations; removed messages free their ids.\n")
	b.WriteString("messages:\n")
	if len(names) == 0 {
		b.WriteString("  {}\n")
	} else {
		for _, name := range names {
			fmt.Fprintf(&b, "  %s: %d\n", name, messages[name])
		}
	}
	return os.WriteFile(path, []byte(b.String()), 0o644)
}
